paths:
  data_raw: "data/raw"
  data_processed: "data/processed"
  data_embeddings: "data/vectorstore"

rag:
  chunk_size: 500
  chunk_overlap: 50
  embedding_model: "mistral-embed"

llm:
  provider: "mistral"
  model_name: "mistral-small-latest"

tools:
  weather_api_key: "YOUR_WEATHER_API_KEY"

app:
  title: "Assistant RAG + Agents"